version: '3'
services:
  au_revoir:
    build: .
    ports:
      - 9061:5000
    read_only: true
    cap_drop:
      - all

    restart: on-failure

    deploy:
        resources:
            limits:
              cpus: '0.2'
              memory: 1000M
