version: '3'
services:
  same_same_but_different:
    build: .
    ports:
      - 9053:10001
    read_only: true
    cap_drop:
      - all

    restart: on-failure

    deploy:
        resources:
            limits:
              cpus: '0.2'
              memory: 1000M
